Feature: Login into a account.
Existing account holder. Client can access his account by using correct username and password.

Scenario: Login into account with correct details
Given User navigate to the website.
And User click on the check box
And User click on continue button on homepage
And User select an option
When User click on continue 
Then UserTwo click on close if no dates

And UserTwo click on the check box
And UserTwo click on continue button on homepage
And UserTwo select an option
When UserTwo click on continue  
Then  UserTwo click on close if no dates
 
 And UserThree click on the check box
And UserThree click on continue button on homepage
And UserThree select an option
When UserThree click on continue
Then  UserThree click on close if no dates 

 And UserFour click on the check box
And UserFour click on continue button on homepage
And UserFour select an option
When UserFour click on continue
Then  UserFour click on close if no dates 

 And UserFive click on the check box
And UserFive click on continue button on homepage
And UserFive select an option
When UserFive click on continue
Then  UserFive click on close if no dates
